version: "3.7"

services:
  db:
    image: postgres
    container_name: wm-db
    restart: always
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=wm-db
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: wm-back
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/app
    links:
      - db
    depends_on:
      - db

volumes:
  pgdata:
    driver: local
