name: CI

on:
  push:
    branches: [ master ]
    
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup NodeJs
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          
      - name: Install Dependecies
        run: yarn
        
      - name: Build
        run: yarn build
        
      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: "., !node_modules, !ormconfig.json, !docker-compose.yml"
          target: "~/app/wm-api"
 
 
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_DEBUG: false
          envkey_SOME_API_KEY: "DATABASE_URL"
          envkey_SECRET_KEY: ${{ secrets.TEST_CLIENT }}
          file_name: .env
          
      - name: Update API
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/app/wm-api
            yarn
            npx prisma migrate deploy --schema=./src/shared/infra/prisma/schema.prisma
            pm2 restart wm-api
